name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies
        run: |
          poetry install

      - name: Lint (Black, isort)
        run: |
          poetry run black --check src tests
          poetry run isort --check-only src tests

      - name: Type Check (Mypy)
        run: |
          poetry run mypy src tests
